export const METRICS_SUBSCRIBER_SERVICE = 'METRICS_SUBSCRIBER_SERVICE';
export const METRICS_PATCH_REQUESTED = 'METRICS_PATCH_REQUESTED';
export const METRICS_PATCH_COMMITTED = 'METRICS_PATCH_COMMITTED';
